fix openwrt

diff --git a/distros/openwrt/clarissa.init b/distros/openwrt/clarissa.init
--- a/distros/openwrt/clarissa.init
+++ b/distros/openwrt/clarissa.init
@@ -10,9 +10,15 @@ USE_PROCD=1
 
 start_service()
 {
-	procd_open_instance
-	procd_set_param command /opt/clarissa/clarissa/clarissa_static
-	procd_append_param command -pI br-lan
-	procd_set_param respawn
-	procd_close_instance
+	. "${IPKG_INSTROOT}/lib/functions/network.sh"
+
+	if network_get_device dev lan; then
+		procd_open_instance
+		procd_set_param command /usr/bin/clarissa
+		procd_append_param command -I "$dev"
+		procd_set_param respawn
+		procd_close_instance
+	else
+		echo "Unable to determine LAN interface" >&2
+	fi
 }
